# dbt and dbt-coves versions can be set i.e. datacoves/dbt-coves:0.19.2-0.20.0a3
image: datacoves/dbt-coves:latest

stages:
  - prep
  - test
  - docs
  - deploy

variables:
  DBT_USER: $DBT_TEST_USER
  DBT_PASSWORD: $DBT_TEST_PASSWORD
  DBT_DATABASE: $DBT_TEST_DATABASE
  DBT_PROFILES_DIR: .config
{ %- if cookiecutter.adapter == "spark" % }
  DBT_DATABRICKS_DRIVER_PATH: $DBT_DATABRICKS_DRIVER_PATH
  DBT_DATABRICKS_HOST: $DBT_DATABRICKS_HOST
  DBT_DATABRICKS_TOKEN: $DBT_DATABRICKS_TOKEN
  DBT_DATABRICKS_CLUSTER: $DBT_DATABRICKS_CLUSTER
{ %- endif % }
{%- if cookiecutter.adapter == "snowflake" %}
  DBT_SNOWFLAKE_ACCOUNT: $DBT_SNOWFLAKE_ACCOUNT
  DBT_SNOWFLAKE_ROLE: $DBT_SNOWFLAKE_ROLE
  DBT_SNOWFLAKE_WAREHOUSE: $DBT_SNOWFLAKE_WAREHOUSE
{%- endif %}
{%- if cookiecutter.adapter == "redshift" %}
  DBT_REDSHIFT_ACCOUNT: $DBT_REDSHIFT_ACCOUNT
{%- endif %}

before_script:
  - dbt deps

setup:
  stage: prep
  script:
  - dbt seed --full-refresh
  - dbt run

lint:
  stage: test
  needs: ["setup"]
  script:
  - dbt-coves check --no-fix

test:
  stage: test
  needs: ["setup"]
  script:
  - dbt test

dbt_docs:
  stage: docs
  needs: ["lint","test"]
  script:
  - dbt docs generate
  - mv target public
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - public
    expire_in: 4 weeks

pages:
  stage: deploy
  script:
  - dbt docs generate
  - mv target public
  artifacts:
    paths:
    - public
