name: Seed, Run, Check, Test and Docs

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Main CI
    runs-on: ubuntu-latest
    env:
      DBT_USER: {% raw %}${{ secrets.DBT_PROD_USER }}{% endraw %}
      DBT_PASSWORD: {% raw %}${{ secrets.DBT_PROD_PASSWORD }}{% endraw %}
      DBT_DATABASE: {% raw %}${{ secrets.DBT_PROD_DATABASE }}{% endraw %}
      DBT_PROFILES_DIR: .config
{%- if cookiecutter.adapter == "snowflake" %}
      DBT_SNOWFLAKE_ACCOUNT: {% raw %}${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}{% endraw %}
      DBT_SNOWFLAKE_ROLE: {% raw %}${{ secrets.DBT_SNOWFLAKE_ROLE }}{% endraw %}
      DBT_SNOWFLAKE_WAREHOUSE: {% raw %}${{ secrets.DBT_SNOWFLAKE_WAREHOUSE }}{% endraw %}
{%- endif %}
{%- if cookiecutter.adapter == "redshift" %}
      DBT_REDSHIFT_ACCOUNT: {% raw %}${{ secrets.DBT_REDSHIFT_ACCOUNT }}{% endraw %}
{%- endif %}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: seed
        uses: datacoves/dbt-coves-action@v1
        with:
          command: "dbt seed --full-refresh"

      - name: seed
        uses: datacoves/dbt-coves-action@v1
        with:
          command: "dbt run"

      - name: lint
        uses: datacoves/dbt-coves-action@v1
        with:
          command: "dbt-coves check --no-fix"

      - name: test
        uses: datacoves/dbt-coves-action@v1
        with:
          command: "dbt test"

      - name: generate docs
        uses: datacoves/dbt-coves-action@v1
        with:
          command: "dbt docs generate"

      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: target